[package]
name = "rust-ffv1"
version = "0.1.0"
authors = ["Luni-4 <luni-4@hotmail.it>"]
edition = "2018"

[dependencies]
av-codec = "^0.2"
av-data = "^0.3"
av-format = "^0.3"
ffv1 = { path = "../../" }
matroska = { version = "0.1.0", git = "https://github.com/rust-av/matroska" }
